In [2]:
import numpy as np

# N1
A = np.array([[1,2,1],[-2,1,1]])

B = np.array([[3,1],[-1,0],[2,4]])

C = np.array([[-2,2],[1,-1],[1,2]])

# A + 2B
print(" A + 2B =")
result_1 = A + 2 * np.transpose(B)
print(result_1)


# B + 2C
print()
print("B + 2C =")
result_2 = B + 2 * C
print(result_2)


 A + 2B =
[[7 0 5]
 [0 1 9]]

B + 2C =
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [67]:
# N2
import numpy as np

arr = np.zeros((8,8), dtype=np.int8)

print("нулевая матрица 8х8:")
print(arr)

slice = arr[0:8:2,1:8:2]
slice[:4][:4] = 1

slice = arr[1:8:2,0:8:2]
slice[:4][:4] = 1

print("\nединицы в шахматном порядке:")
print(arr)

нулевая матрица 8х8:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

единицы в шахматном порядке:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [85]:
# N3*

import numpy as np

print("Вектор_1 от 0 до 1,4 с шагом 0,1:")
vektor_1 = np.arange(0,1.5,0.1)
print(vektor_1)

print("\nВектор_2 от 1 до 6 с шагом 1:")
vektor_2 = np.arange(1,7,1)
print(vektor_2)

print("\nМатрица_1 5х3 преобразованная из первого вектора:")
arr_1 = vektor_1.reshape((5,3))
print(arr_1)

print("\nМатрица_2 3х2 преобразованная из второго вектора:")
arr_2 = vektor_2.reshape((3,2))
print(arr_2)

print("\nРезультат умножения Матрица_1 на Матрица_2:")
result = np.dot(arr_1,arr_2)
print(result)

Вектор_1 от 0 до 1,4 с шагом 0,1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]

Вектор_2 от 1 до 6 с шагом 1:
[1 2 3 4 5 6]

Матрица_1 5х3 преобразованная из первого вектора:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]

Матрица_2 3х2 преобразованная из второго вектора:
[[1 2]
 [3 4]
 [5 6]]

Результат умножения Матрица_1 на Матрица_2:
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [84]:
# N4*

import numpy as np

print("Вектор размерностью 36 от 1 с шагом 2:")
arr = np.arange(1,73,2,dtype=np.int32)
print(arr)

print("\nвектор с кратными 3:")
result = arr[1:36:3]
print(result)

Вектор размерностью 36 от 1 с шагом 2:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]

вектор с кратными 3:
[ 3  9 15 21 27 33 39 45 51 57 63 69]
